package cn.com.upcard.mgateway.channel.bank.mybank.common;

import cn.com.upcard.mgateway.channel.bank.cib.common.CibResponseCode;
import cn.com.upcard.mgateway.common.enums.ResponseResult;

public enum MyBankResponseCode {

	// 全局返回码部分
	SGW01002("SGW01002",ResponseResult.TRADE_FAILED),
	SGW11009("SGW11009",ResponseResult.TRADE_FAILED),
	SGW12001("SGW12001",ResponseResult.TRADE_FAILED),
	SGW12014("SGW12014",ResponseResult.TRADE_FAILED),
	SGW12016("SGW12016",ResponseResult.TRADE_FAILED),
	SGW21008("SGW21008",ResponseResult.NON_RESP),
	SGW21010("SGW21010",ResponseResult.TRADE_FAILED),
	SGW21013("SGW21013",ResponseResult.SYSTEM_ERROR),
	SGW31001("SGW31001",ResponseResult.NON_RESP),
	SGW31004("SGW31004",ResponseResult.TRADE_FAILED),
	SGW31005("SGW31005",ResponseResult.TRADE_FAILED),
	SGW81000("SGW81000",ResponseResult.TRADE_FAILED),
	SGW81001("SGW81001",ResponseResult.TRADE_FAILED),	
	// 业务返回码
	MT_BUYER_PAY_MONTH_ACCUM_AMT_MORE_THAN_LIMIT("MT_BUYER_PAY_MONTH_ACCUM_AMT_MORE_THAN_LIMIT",ResponseResult.TRADE_FAILED),
	MT_AWAKE_MOBILE_CASHIER_FAIL("MT_AWAKE_MOBILE_CASHIER_FAIL", ResponseResult.TRADE_FAILED),
	MT_TRADE_INFO_IS_TAMPER("MT_TRADE_INFO_IS_TAMPER", ResponseResult.TRADE_FAILED),
	MT_PAY_AUTH_CODE_IS_DISABLED("MT_PAY_AUTH_CODE_IS_DISABLED", ResponseResult.AUTH_CODE_INVALID),
	MT_DISCORDANT_REPEAT_REQUEST("MT_DISCORDANT_REPEAT_REQUEST", ResponseResult.TRADE_FAILED),
	MT_ORDER_AMT_MORE_THAN_LIMIT("MT_ORDER_AMT_MORE_THAN_LIMIT", ResponseResult.AMOUNT_TOO_LARGE),
	MT_PAY_ORDER_NOT_EXISTS("MT_PAY_ORDER_NOT_EXISTS", ResponseResult.TRADE_FAILED),
	MT_PAY_ORDER_PAID("MT_PAY_ORDER_PAID", ResponseResult.ORDER_HAVA_PAID),
	MT_BUYER_PAY_FUNCTION_IS_CLOSED("MT_BUYER_PAY_FUNCTION_IS_CLOSED", ResponseResult.TRADE_FAILED),
	MT_PAY_REQUEST_IN_PROCESS("MT_PAY_REQUEST_IN_PROCESS", ResponseResult.WAIT_PAYING),
	MT_MERCH_ROLE_INVALID("MT_MERCH_ROLE_INVALID", ResponseResult.TRADE_FAILED),
	MT_NOT_COMPLY_AR_CONSTRAINTN("MT_NOT_COMPLY_AR_CONSTRAINTN", ResponseResult.TRADE_FAILED),
	MT_ACCESS_LIMITED("MT_ACCESS_LIMITED", ResponseResult.TRADE_FAILED),
	MT_BUYER_ACCOUNT_STATUS_ERROR("MT_BUYER_ACCOUNT_STATUS_ERROR", ResponseResult.TRADE_FAILED),
	MT_PAY_ORDER_CLOSED("MT_PAY_ORDER_CLOSED", ResponseResult.ORDER_CLOSED),
	MT_PAY_ORDER_STATUS_ERROR("MT_PAY_ORDER_STATUS_ERROR", ResponseResult.ORDER_HAVA_PAID),
	MT_NOT_AUTH("MT_NOT_AUTH", ResponseResult.TRADE_FAILED),
	MT_MERCH_RECEIVER_LIMIT_IS_MORE_THEN_LIMIT("MT_MERCH_RECEIVER_LIMIT_IS_MORE_THEN_LIMIT", ResponseResult.ORDER_HAVA_PAID),
	MT_BUYER_BALANCE_AMT_IS_NOT_ENOUGH("MT_BUYER_BALANCE_AMT_IS_NOT_ENOUGH", ResponseResult.BALANCE_NOT_ENOUGH),
	MT_TRADE_BUYER_IS_NOT_MATCHED("MT_TRADE_BUYER_IS_NOT_MATCHED", ResponseResult.TRADE_FAILED),
	MT_ISV_ORG_ID_NOT_EXIST("MT_ISV_ORG_ID_NOT_EXIST", ResponseResult.TRADE_FAILED),
	MT_MERCH_STORE_ID_IS_INVALID("MT_MERCH_STORE_ID_IS_INVALID", ResponseResult.TRADE_FAILED),
	MT_ILLEGAL_PARAMETER("MT_ILLEGAL_PARAMETER", ResponseResult.TRADE_FAILED),
	MT_SYSTEM_CONFIG_ERROR("MT_SYSTEM_CONFIG_ERROR", ResponseResult.TRADE_FAILED),
	MT_FORBIDDEN_TRADE_TIME("MT_FORBIDDEN_TRADE_TIME", ResponseResult.TRADE_FAILED),
	MT_MERCH_APPID_IS_NOT_MATCH_WITH_OPENID("MT_MERCH_APPID_IS_NOT_MATCH_WITH_OPENID", ResponseResult.APPID_NOT_MATCH_OPENID),
	MT_ISV_AR_INVALID("MT_ISV_AR_INVALID", ResponseResult.TRADE_FAILED),
	MT_ORDER_INFO_CONTAINED_FORBIDDEN_WORDS("MT_ORDER_INFO_CONTAINED_FORBIDDEN_WORDS", ResponseResult.TRADE_FAILED),
	MT_MERCH_AR_INVALID("MT_MERCH_AR_INVALID", ResponseResult.TRADE_FAILED),
	MT_ISV_ROLE_INVALID("MT_ISV_ROLE_INVALID", ResponseResult.TRADE_FAILED),
	MT_SYSTEMERROR("MT_SYSTEMERROR", ResponseResult.TRADE_FAILED),
	MT_MERCH_ID_NOT_EXIST("MT_MERCH_ID_NOT_EXIST", ResponseResult.NO_INVOKE_PERMISSION),
	MT_MERCH_RECEIVER_MONTH_ACCUM_AMT_MORE_THAN_LIMIT("MT_MERCH_RECEIVER_MONTH_ACCUM_AMT_MORE_THAN_LIMIT", ResponseResult.TRADE_FAILED),
	MT_VALUD_OF_SUB_OPENID_DISABLED("MT_VALUD_OF_SUB_OPENID_DISABLED", ResponseResult.OPENID_IS_INVALID),
	MT_BUYER_PAY_DAILY_ACCUM_AMT_MORE_THAN_LIMIT("MT_BUYER_PAY_DAILY_ACCUM_AMT_MORE_THAN_LIMIT", ResponseResult.TRADE_FAILED),
	MT_PAY_ORDER_ACCEPT_FAILED("MT_PAY_ORDER_ACCEPT_FAILED", ResponseResult.TRADE_FAILED),

	MT_ORDER_TYPE_NO_SUPPORT_CLOSE_ERROR("MT_ORDER_TYPE_NO_SUPPORT_CLOSE_ERROR", ResponseResult.TRADE_FAILED),
	MT_ACCEPT_FAIL("MT_ACCEPT_FAIL", ResponseResult.TRADE_FAILED),
    MT_PAY_ORDER_CANCEL("MT_PAY_ORDER_CANCEL",ResponseResult.ORDER_REVERSED),
    MT_USER_PAYING("MT_USER_PAYING", ResponseResult.WAIT_PAYING),
    MT_AUTH_CODE_PAY_FAILURE("MT_AUTH_CODE_PAY_FAILURE", ResponseResult.AUTH_CODE_INVALID), 
    MT_CANCEL_TOO_SOON("MT_CANCEL_TOO_SOON",ResponseResult.TRADE_FAILED),
    MT_REFUND_ORDER_NOT_EXISTS("MT_REFUND_ORDER_NOT_EXISTS",ResponseResult.TRADE_FAILED), 
    MT_REFUND_TOO_MUCH("MT_REFUND_TOO_MUCH",ResponseResult.REFUND_AMOUNT_OUT_RANGE), 
    MT_REFUND_OVERDUE("MT_REFUND_OVERDUE", ResponseResult.TRADE_FAILED),
    MT_REFUND_FAIL("MT_REFUND_FAIL", ResponseResult.TRADE_FAILED);
	
	private String resultCode;
	private ResponseResult responseResult;

	public String getResultCode() {
		return resultCode;
	}

	public ResponseResult getResponseResult() {
		return responseResult;
	}

	private MyBankResponseCode() {
	}

	private MyBankResponseCode(String resultCode, ResponseResult responseResult) {
		this.resultCode = resultCode;
		this.responseResult = responseResult;
	}

	public static ResponseResult transferCode(String resultCode) {
		if (resultCode == null || resultCode.equals("")) {
			return ResponseResult.ORDER_STATUS_ERROR;
		}
		for (CibResponseCode cibCode : CibResponseCode.values()) {
			if (cibCode.getResultCode().equals(resultCode)) {
				return cibCode.getResponseResult();
			}
		}
		return ResponseResult.ORDER_STATUS_ERROR;
	}
}
